services:
  # Laravel Application Service
  app:
    build:
      context: .
      dockerfile: ./configs/php/Dockerfile
    image: health10-app
    container_name: health10-app
    volumes:
      - ./src:/var/www/html
    networks:
      - health10_network  # Define the network here
    environment:
       - APP_KEY=${APP_KEY:-base64:defaultkey}  # Set a default APP_KEY if not provided
       - DB_CONNECTION=mysql
       - DB_HOST=${APP_DB_HOST:-127.0.0.1}
       - DB_PORT=${APP_DB_PORT:-3306}
       - DB_DATABASE=${APP_DATABASE:-laravel}
       - DB_USERNAME=${APP_DB_USERNAME:-root}
       - DB_PASSWORD=${APP_PASSWORD:-helthcarepwd}
       
  nginx:
    build:
      context: .
      dockerfile: ./configs/nginx/Dockerfile
    image: nginx-health10
    container_name: health10-nginx    
    ports:
      - "${APP_PORT:-8088}:${NGINX_PORT:-80}"
    environment:
      - NGINX_PORT=${NGINX_PORT:-80}
      - HTTPS_ENABLED=${HTTPS_ENABLED:-false}
    volumes:
      - ./src:/var/www/html
      - ./configs/certs:/etc/nginx/certs
    depends_on:
      - app
    networks:
      - health10_network

  # Database Service (MySQL)
  db:
    image: mysql:9.6.0
    container_name: health10-db
    environment:
      MYSQL_DATABASE: ${APP_DATABASE:-helthcare}
      MYSQL_ROOT_PASSWORD: ${APP_PASSWORD:-helthcarepwd}
    ports:
      - "${APP_DB_HOST_FORWERD_TO:-33306}:3306"  # Map port 33306 on host to port 3306 in the container
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - health10_network  # Reference the same network here

  # Node.js Service
  node:
    build:
      context: .
      dockerfile: ./configs/node/Dockerfile
    image: health10-node
    container_name: health10-node   
    volumes:
      - ./src:/var/www/html
      - /var/www/html/node_modules
      - ./configs/certs:/certs
    networks:
      - health10_network
    environment:
      - VITE_PORT=${VITE_PORT:-5173}
      - VITE_HOST=${VITE_HOST:-0.0.0.0}
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
  redis:
    image: redis:7-alpine
    container_name: health10-redis
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-null}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - health10_network
  mailpit:
    image: axllent/mailpit
    container_name: health10-mailpit
    restart: unless-stopped
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025"
      - "${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - health10_network    
networks:
  health10_network:
    driver: bridge
